// Generated by GSE. Edit at your own risk.

#if !defined(USER_IMAGE_RESOURCE_H)
#define USER_IMAGE_RESOURCE_H

#define USER_IMAGE_TABLE            \
ENTRY(IMG_ANIMATION, "Standard/Animation.png", false)    \
ENTRY(IMG_BACK, "Standard/Back.png", false)    \
ENTRY(IMG_BUTTONS, "Standard/Buttons.png", false)    \
ENTRY(IMG_CAROUSEL, "Standard/Carousel.png", false)    \
ENTRY(IMG_GAUGEANDWHEEL, "Standard/GaugeAndWheel.png", false)    \
ENTRY(IMG_KNOB, "Standard/Knob.png", false)    \
ENTRY(IMG_PROGRESSFG_HORI, "Standard/ProgressFG_Hori.png", false)    \
ENTRY(IMG_PROGRESSFG_VERT, "Standard/ProgressFG_Vert.png", false)    \
ENTRY(IMG_SETTINGS, "Standard/Settings.png", false)    \
ENTRY(IMG_SLIDER, "Standard/Slider.png", false)    \
ENTRY(IMG_SLIDERHORI, "Standard/SliderHori.png", false)    \
ENTRY(IMG_SLIDERVERTI, "Standard/SliderVerti.png", false)    \
ENTRY(IMG_TEXT, "Standard/Text.png", false)    \
ENTRY(IMG_WHEEL_BG, "Standard/Wheel_BG.png", false)    \
ENTRY(IMG_BACKGROUNDIMAGE, "Standard/BackgroundImage.png", false)    \
ENTRY(IMG_EASINGBUTTON, "Standard/EasingButton.png", false)    \
ENTRY(IMG_EASINGBUTTON_F, "Standard/EasingButton_F.png", false)    \
ENTRY(IMG_EASINGBUTTON_G, "Standard/EasingButton_G.png", false)    \
ENTRY(IMG_EASINGBUTTON_H, "Standard/EasingButton_H.png", false)    \
ENTRY(IMG_EASINGBUTTON_P, "Standard/EasingButton_P.png", false)    \
ENTRY(IMG_PROGRESSBG, "Standard/ProgressBG.png", false)    \
ENTRY(IMG_BUTTON, "Standard/Button.png", false)    \
ENTRY(IMG_BUTTON_F, "Standard/Button_F.png", false)    \
ENTRY(IMG_BUTTON_H, "Standard/Button_H.png", false)    \
ENTRY(IMG_BUTTON_P, "Standard/Button_P.png", false)    \
ENTRY(IMG_BUTTONDOWN, "Standard/ButtonDown.png", false)    \
ENTRY(IMG_BUTTONUP, "Standard/ButtonUp.png", false)    \
ENTRY(IMG_SLIDERBAR, "Standard/SliderBar.png", false)    \
ENTRY(IMG_SCROLLSLIDER, "Standard/ScrollSlider.png", false)    \
ENTRY(IMG_ANIMATABLEOBJECT, "Standard/AnimatableObject.png", false)    \
ENTRY(IMG_CAROUSELIMG, "Standard/CarouselImg.png", false)    \
ENTRY(IMG_NEEDLE, "Standard/Needle.png", false)    \
ENTRY(IMG_CUSTOM_GAUGE, "Standard/GaugeNew.png", false)    \
ENTRY(IMG_TEXTINPUT, "Standard/TextInput.png", false)    \
ENTRY(IMG_TEXTINPUT_H, "Standard/TextInput_H.png", false)    \
ENTRY(IMG_TEXTINPUT_P, "Standard/TextInput_P.png", false)    \
ENTRY(IMG_KEY_P, "Standard/Key_P.png", false)    \
ENTRY(IMG_KEY_H, "Standard/Key_H.png", false)    \
ENTRY(IMG_KEY, "Standard/Key.png", false)    \
ENTRY(IMG_KEYBOARD, "Standard/Keyboard.png", false)    \
ENTRY(IMG_SCRATCHPAD, "Standard/Scratchpad.png", false)    \
ENTRY(IMG_COMBOBUTTON, "Standard/ComboButton.png", false)    \
ENTRY(IMG_COMBOBUTTON_H, "Standard/ComboButton_H.png", false)    \
ENTRY(IMG_COMBOBUTTON_P, "Standard/ComboButton_P.png", false)    \
ENTRY(IMG_COMBOTEXT, "Standard/ComboText.png", false)    \
ENTRY(IMG_COMBOTEXT_H, "Standard/ComboText_H.png", false)    \
ENTRY(IMG_COMBOTEXT_P, "Standard/ComboText_P.png", false)    \
ENTRY(IMG_INFO, "Standard/Info.png", false)    \
ENTRY(IMG_GUILIANI_DEMO_BACKGROUND_NATIVE, "Standard/guiliani_demo_background_native.png", true)    \
ENTRY(IMG_GUILIANI_DEMO_BACKGROUND_RAW, "Standard/guiliani_demo_background_raw.png", false)    \
ENTRY(IMG_GUILIANI_DEMO_BACKGROUND_RLE, "Standard/guiliani_demo_background_rle.png", false)    \
ENTRY(IMG_TOP_BAR, "top_bar.png", false)    \
ENTRY(IMG_BOTTOM_BAR, "bottom_bar.png", false)    \
ENTRY(IMG_CHECKBOX_BLUE_NOTSELECTED, "Standard/checkbox_blue_notselected.png", false)    \
ENTRY(IMG_CHECKBOX_BLUE_SELECTED, "Standard/checkbox_blue_selected.png", false)    \
ENTRY(IMG_CHECKBOX_GRAY_NOTSELECTED, "Standard/checkbox_gray_notselected.png", false)    \
ENTRY(IMG_CHECKBOX_GRAY_SELECTED, "Standard/checkbox_gray_selected.png", false)    \
ENTRY(IMG_CHECKBOX_GREEN_NOTSELECTED, "Standard/checkbox_green_notselected.png", false)    \
ENTRY(IMG_CHECKBOX_GREEN_SELECTED, "Standard/checkbox_green_selected.png", false)    \
ENTRY(IMG_RADIOBUTTON_BLUE_NOTSELECTED, "Standard/radiobutton_blue_notselected.png", false)    \
ENTRY(IMG_RADIOBUTTON_BLUE_SELECTED, "Standard/radiobutton_blue_selected.png", false)    \
ENTRY(IMG_RADIOBUTTON_GRAY_NOTSELECTED, "Standard/radiobutton_gray_notselected.png", false)    \
ENTRY(IMG_RADIOBUTTON_GRAY_SELECTED, "Standard/radiobutton_gray_selected.png", false)    \
ENTRY(IMG_RADIOBUTTON_GREEN_NOTSELECTED, "Standard/radiobutton_green_notselected.png", false)    \
ENTRY(IMG_RADIOBUTTON_GREEN_SELECTED, "Standard/radiobutton_green_selected.png", false)    \
ENTRY(IMG_SWITCH_BLUE_OFF, "Standard/switch_blue_off.png", false)    \
ENTRY(IMG_SWITCH_BLUE_ON, "Standard/switch_blue_on.png", false)    \
ENTRY(IMG_SWITCH_GRAY_OFF, "Standard/switch_gray_off.png", false)    \
ENTRY(IMG_SWITCH_GRAY_ON, "Standard/switch_gray_on.png", false)    \
ENTRY(IMG_SWITCH_GREEN_OFF, "Standard/switch_green_off.png", false)    \
ENTRY(IMG_SWITCH_GREEN_ON, "Standard/switch_green_on.png", false)    \
ENTRY(IMG_ROUND_BUTTON_HOVER_BLUE, "Standard/round_button_hover_blue.png", false)    \
ENTRY(IMG_ROUND_BUTTON_PRESSED_GREEN, "Standard/round_button_pressed_green.png", false)    \
ENTRY(IMG_ROUND_BUTTON_STD_GRAY, "Standard/round_button_std_gray.png", false)    \
ENTRY(IMG_CAROUSELIMG2, "Standard/CarouselImg2.png", false)    \
ENTRY(IMG_CAROUSELIMG3, "Standard/CarouselImg3.png", false)    \
ENTRY(IMG_CAROUSELIMG4, "Standard/CarouselImg4.png", false)    \
ENTRY(IMG_CAROUSELIMG5, "Standard/CarouselImg5.png", false)    \
ENTRY(LAST_GENERATED_IMAGE_ID, "", true)

#endif // USER_IMAGE_RESOURCE_H
