// Generated by GSE. Edit at your own risk.

#if !defined(USER_FONT_RESOURCE_H)
#define USER_FONT_RESOURCE_H

#define USER_FONT_TABLE            \
ENTRY(HEADER_FNT, "BebasNeue Bold.otf", 28, 0, false)    \
ENTRY(MENU_FONT, "BebasNeue Book.otf", 24, 0, false)    \
ENTRY(FNT_BEBASNEUE_REGULAR, "BebasNeue Regular.otf", 20, 0, false)    \
ENTRY(FNT_BEBASNEUE_BOLD, "BebasNeue Bold.otf", 20, 0, false)    \
ENTRY(FNT_BEBASNEUE_ITALIC, "BebasNeue Light.otf", 20, 0, false)    \
ENTRY(FNT_BEBASNEUE_BOLD_ITALIC, "BebasNeue Book.otf", 20, 0, false)    \
ENTRY(FNT_BEBASNEUE_BOOK, "BebasNeue Book.otf", 32, 0, false)    \
ENTRY(FNT_BEBASNEUE_BOLD_WHEEL, "BebasNeue Bold.otf", 32, 0, false)    \
ENTRY(LAST_GENERATED_FONT_ID, "",0 ,0 , true)

#endif // USER_FONT_RESOURCE_H
